In [1]:
from cvxopt_interface import cvxopt_solve

In [6]:
# =================
# Import Statements
# =================
import numpy as np
import pyomo.environ as pyo
from pyomo.environ import units
from pyomo.contrib.edi import Formulation
from pyomo.contrib.edi import BlackBoxFunctionModel
from cvxopt_interface import cvxopt_solve
f = Formulation()

cst = f.Constant(name = 'c',  value = 3.0, units = '-', size = 0, description = 'A constant')
c2  = f.Constant(name = 'c2', value = 2,   units = '-', size = 0, description = 'A constant')
x   = f.Variable(name = 'x',  guess = 1.0, units = '-', size = 0, description = 'The X variable')
y   = f.Variable(name = 'y',  guess = 2.0, units = '-', size = 0, description = 'The Y variable')


f.Objective( x**2 + 4*y**c2 - 8*x - 16*y +1 + x*y )
f.ConstraintList(
    [
        x + y <= 5,
        x <= 3,
        x >= 0,
        y >= 0,
        x + y == cst,
    ]
)

res = cvxopt_solve(f)
print(res)
print(res['x'])

{'x': <2x1 matrix, tc='d'>, 'y': <1x1 matrix, tc='d'>, 's': <4x1 matrix, tc='d'>, 'z': <4x1 matrix, tc='d'>, 'status': 'optimal', 'gap': 1.7549473121336217e-07, 'relative gap': 7.778159832171176e-09, 'primal objective': -22.5625, 'dual objective': -22.56250017549473, 'primal infeasibility': 6.595707599932383e-17, 'dual infeasibility': 4.0222862694186495e-09, 'primal slack': 1.3749999891820195, 'dual slack': 1.728711526531591e-08, 'iterations': 4, 'objective_shift': 1.0, 'problem_structure': 'quadratic_program'}
[ 1.63e+00]
[ 1.37e+00]



In [2]:
# =================
# Import Statements
# =================
import numpy as np
import pyomo.environ as pyo
from pyomo.environ import units
from pyomo.contrib.edi import Formulation
from pyomo.contrib.edi import BlackBoxFunctionModel
from cvxopt_interface import cvxopt_solve
f = Formulation()

cst = f.Constant(name = 'c',  value = 3.0, units = '-', size = 0, description = 'A constant')
c2  = f.Constant(name = 'c2', value = 2,   units = '-', size = 0, description = 'A constant')
x   = f.Variable(name = 'x',  guess = 1.0, units = '-', size = 0, description = 'The X variable')
y   = f.Variable(name = 'y',  guess = 2.0, units = '-', size = 0, description = 'The Y variable')


f.Objective( x**2 + 4*y**c2 +1 + x*y )
f.ConstraintList(
    [
        # x + y <= 5,
        # x <= 3,
        # x >= 0,
        # y >= 0,
        x + 1/(1+y*x) == cst,
        # (x+y*x**2)/(1+y*x) + 1/(1+y*x) == cst,
        # (x + y*x**2 + 1)/(1+y*x) == cst,
    ]
)

res = cvxopt_solve(f)
print(res)
print(res['x'])

ValueError: Could not convert the formulation to a valid CVXOPT structure (LP,QP,GP)

In [3]:
# =================
# Import Statements
# =================
import numpy as np
import pyomo.environ as pyo
from pyomo.environ import units
from pyomo.contrib.edi import Formulation
from pyomo.contrib.edi import BlackBoxFunctionModel
f = Formulation()
cst = f.Constant(name = 'c', value = 2.0 + 1/2, units = '-', size = 0, description = 'A constant')

x1 = f.Variable(name = 'x_1', 
              guess = 0.0, 
              units = '-', 
              size = 0, 
              description = 'Quantity of product 1')

x2 = f.Variable(name = 'x_2', 
              guess = 0.0, 
              units = '-', 
              size = 0, 
              description = 'Quantity of product 2')

f.Objective( -(3 * cst*x1 + 3.4 * x2) )
f.ConstraintList(
    [
        3   * x1 + 4    * x2 <= 20000 + 2000,
        0.3 * x1 + 0.38 * x2 <= 4000 - 400,
        x1 >= 0,
        x2 >= 0
    ]
)

res = cvxopt_solve(f)
print(res)
print(res['x'])

{'x': <2x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 's': <4x1 matrix, tc='d'>, 'z': <4x1 matrix, tc='d'>, 'status': 'optimal', 'gap': 0.00025999454441750434, 'relative gap': 4.727173546431867e-09, 'primal objective': -54999.999865406186, 'dual objective': -55000.00065285537, 'primal infeasibility': 9.054364225617231e-17, 'dual infeasibility': 1.552581374663951e-08, 'primal slack': 6.966428894057896e-07, 'dual slack': 9.85840758526536e-09, 'residual as primal infeasibility certificate': None, 'residual as dual infeasibility certificate': None, 'iterations': 5, 'objective_shift': array([0.]), 'problem_structure': 'linear_program'}
[ 7.33e+03]
[ 6.97e-07]



In [4]:
# ===========
# Description
# ===========
# A simple aircraft sizing problem, formulated as a Geometric Program
# From:  Hoburg and Abbeel
#        Geometric Programming for Aircraft Design Optimization
#        AIAA Journal
#        2014

# =================
# Import Statements
# =================
import numpy as np
import pyomo.environ as pyo
from pyomo.environ import units
from pyomo.contrib.edi import Formulation
from pyomo.contrib.edi import BlackBoxFunctionModel

# ===================
# Declare Formulation
# ===================
f = Formulation()

# =================
# Declare Variables
# =================

A   = f.Variable(name="A",   guess=10.0,    units="-",   description="aspect ratio"              )
C_D = f.Variable(name="C_D", guess=0.025,   units="-",   description="Drag coefficient of wing"  )
C_f = f.Variable(name="C_f", guess=0.003,   units="-",   description="skin friction coefficient" )
C_L = f.Variable(name="C_L", guess=0.5,     units="-",   description="Lift coefficient of wing"  )
D   = f.Variable(name="D",   guess=300,     units="N",   description="total drag force"          )
Re  = f.Variable(name="Re",  guess=3e6,     units="-",   description="Reynold's number"          )
S   = f.Variable(name="S",   guess=10.0,    units="m^2", description="total wing area"           )
V   = f.Variable(name="V",   guess=30.0,    units="m/s", description="cruising speed"            )
W   = f.Variable(name="W",   guess=10000.0, units="N",   description="total aircraft weight"     )
W_w = f.Variable(name="W_w", guess=2500,    units="N",   description="wing weight"               )

# =================
# Declare Constants
# =================
C_Lmax     = f.Constant(name="C_Lmax", value=1.5, units="-", description="max CL with flaps down")
CDA0       = f.Constant(name="CDA0",   value=0.031, units="m^2", description="fuselage drag area")
e          = f.Constant(name="e",      value=0.95, units="-", description="Oswald efficiency factor")
k          = f.Constant(name="k",      value=1.2, units="-", description="form factor")
mu         = f.Constant(name="mu",     value=1.78e-5, units="kg/m/s", description="viscosity of air")
N_ult      = f.Constant(name="N_ult",  value=3.8, units="-", description="ultimate load factor")
rho        = f.Constant(name="rho",    value=1.23, units="kg/m^3", description="density of air")
S_wetratio = f.Constant(name="Srat",   value=2.05, units="-", description="wetted area ratio")
tau        = f.Constant(name="tau",    value=0.12, units="-", description="airfoil thickness to chord ratio")
V_min      = f.Constant(name="V_min",  value=22, units="m/s", description="takeoff speed")
W_0        = f.Constant(name="W_0",    value=4940.0, units="N", description="aircraft weight excluding wing")
W_W_coeff1 = f.Constant(name="W_c1",   value=8.71e-5, units="1/m", description="Wing Weight Coefficient 1")
W_W_coeff2 = f.Constant(name="W_c2",   value=45.24, units="Pa", description="Wing Weight Coefficient 2")

# =====================
# Declare the Objective
# =====================
f.Objective(D)

# ===================================
# Declare some intermediate variables
# ===================================
pi = np.pi
W_w_strc = W_W_coeff1 * (N_ult * A**1.5 * (W_0 * W * S) ** 0.5) / tau
W_w_surf = W_W_coeff2 * S

# =======================
# Declare the Constraints
# =======================
f.ConstraintList(
    [
        C_D >= CDA0/S + k*C_f*S_wetratio + C_L**2/(pi*A*e), 
        W_w >= W_w_surf + W_w_strc,
        D >= 0.5 * rho * S * C_D * V**2,
        Re == (rho / mu) * V * (S / A) ** 0.5,
        C_f == 0.074 / Re**0.2,
        W == 0.5 * rho * S * C_L * V**2,
        W == 0.5 * rho * S * C_Lmax * V_min**2,
        W >= W_0 + W_w,
    ]
)

res = cvxopt_solve(f)
print(res)
print(np.exp(res['x']))

{'status': 'optimal', 'x': <10x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 'znl': <12x1 matrix, tc='d'>, 'zl': <0x1 matrix, tc='d'>, 'snl': <12x1 matrix, tc='d'>, 'sl': <0x1 matrix, tc='d'>, 'gap': 5.110304608386722e-10, 'relative gap': 8.943512248015986e-11, 'primal objective': 5.713979278961597, 'dual objective': 5.713979549276498, 'primal slack': 1.8601444398680842e-13, 'dual slack': 0.42065169738159597, 'primal infeasibility': 8.850073400820477e-09, 'dual infeasibility': 3.1801281509240524e-08, 'problem_structure': 'geometric_program'}
[[8.45998434e+00]
 [2.05923273e-02]
 [3.59894112e-03]
 [4.98788754e-01]
 [3.03074691e+02]
 [3.67523311e+06]
 [1.64417922e+01]
 [3.81513565e+01]
 [7.34109581e+03]
 [2.40109663e+03]]


In [7]:
# =================
# Import Statements
# =================
import numpy as np
import pyomo.environ as pyo
from pyomo.environ import units
from pyomo.contrib.edi import Formulation
from pyomo.contrib.edi import BlackBoxFunctionModel

# ===================
# Declare Formulation
# ===================
f = Formulation()


h   = f.Variable(name = 'h', guess = 1.0, units = 'm', description = 'The Y variable')
w   = f.Variable(name = 'w', guess = 1.0, units = 'm', description = 'The X variable')
d   = f.Variable(name = 'd', guess = 1.0, units = 'm', description = 'The Z variable')

Aflr  = f.Constant(name = 'Aflr',  value = 1000  , units = 'm^2', description = 'Area of floor')
Awall = f.Constant(name = 'Awall', value =  100  , units = 'm^2', description = 'Area of wall')
alpha = f.Constant(name = 'alpha', value =    0.5, units = '-',   description = 'Aspect Ratio Constraint')
beta  = f.Constant(name = 'beta',  value =    2  , units = '-',   description = 'Aspect Ratio Constraint')
gamma = f.Constant(name = 'gamma', value =    0.5, units = '-',   description = 'Aspect Ratio Constraint')
delta = f.Constant(name = 'delta', value =    2  , units = '-',   description = 'Aspect Ratio Constraint')

f.Objective( 1/(h*w*d) )
f.ConstraintList(
    [
    2*(h*w + h*d) <= Awall,
    w*d <= Aflr,
    alpha <= h/w,
    h/w <= beta,
    gamma <= d/w,
    d/w <= delta,
    ]
)

res = cvxopt_solve(f)
print(res)
print(res['x'])

{'status': 'optimal', 'x': <3x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 'znl': <6x1 matrix, tc='d'>, 'zl': <0x1 matrix, tc='d'>, 'snl': <6x1 matrix, tc='d'>, 'sl': <0x1 matrix, tc='d'>, 'gap': 1.1952800111771062e-07, 'relative gap': 2.2724659470482912e-08, 'primal objective': -5.259836842570323, 'dual objective': -5.25983690574, 'primal slack': 6.521413955765362e-10, 'dual slack': 3.612751722279948e-10, 'primal infeasibility': 5.853419820581857e-09, 'dual infeasibility': 2.65329495055962e-08, 'problem_structure': 'geometric_program'}
[ 1.06e+00]
[ 1.75e+00]
[ 2.45e+00]



In [8]:
import numpy as np
import pyomo.environ as pyo
from cvxopt_interface import cvxopt_solve

m = pyo.ConcreteModel()

m.d   = pyo.Var()
m.h   = pyo.Var()
m.w   = pyo.Var()

m.Aflr  = pyo.Param( initialize = 1000   )
m.Awall = pyo.Param( initialize =  100   )
m.alpha = pyo.Param( initialize =    0.5 )
m.beta  = pyo.Param( initialize =    2   )
m.gamma = pyo.Param( initialize =    0.5 )
m.delta = pyo.Param( initialize =    2   )

m.objective    = pyo.Objective(  expr = 1/(m.h * m.w * m.d)              )
m.constraint_1 = pyo.Constraint( expr = 2*(m.h*m.w + m.h*m.d) <= m.Awall )
m.constraint_2 = pyo.Constraint( expr = m.w*m.d <= m.Aflr                )
m.constraint_3 = pyo.Constraint( expr = m.alpha <= m.h/m.w               )
m.constraint_4 = pyo.Constraint( expr = m.h/m.w <= m.beta                )
m.constraint_5 = pyo.Constraint( expr = m.gamma <= m.d/m.w               )
m.constraint_6 = pyo.Constraint( expr = m.d/m.w <= m.delta               )

res = cvxopt_solve(m)

print(res)
print(np.exp(res['x']))

{'status': 'optimal', 'x': <3x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 'znl': <6x1 matrix, tc='d'>, 'zl': <0x1 matrix, tc='d'>, 'snl': <6x1 matrix, tc='d'>, 'sl': <0x1 matrix, tc='d'>, 'gap': 1.1952800111771054e-07, 'relative gap': 2.2724659470482896e-08, 'primal objective': -5.259836842570323, 'dual objective': -5.259836905740002, 'primal slack': 6.521413955765451e-10, 'dual slack': 3.612751722279946e-10, 'primal infeasibility': 5.853419803285564e-09, 'dual infeasibility': 2.6532949349966912e-08, 'problem_structure': 'geometric_program'}
[[11.54251112]
 [ 2.88731329]
 [ 5.77462657]]


In [9]:
from cvxopt import matrix, log, exp, solvers

Aflr  = 1000.0
Awall = 100.0
alpha = 0.5
beta  = 2.0
gamma = 0.5
delta = 2.0

F = matrix( [[-1., 1., 1., 0., -1.,  1.,  0.,  0.],
             [-1., 1., 0., 1.,  1., -1.,  1., -1.],
             [-1., 0., 1., 1.,  0.,  0., -1.,  1.]])
g = log( matrix( [1.0, 2/Awall, 2/Awall, 1/Aflr, alpha, 1/beta, gamma, 1/delta]) )
K = [1, 2, 1, 1, 1, 1, 1]

print(F)
print(g)
print(K)

h, w, d = exp( solvers.gp(K, F, g)['x'] )
print(h,w,d)

[-1.00e+00 -1.00e+00 -1.00e+00]
[ 1.00e+00  1.00e+00  0.00e+00]
[ 1.00e+00  0.00e+00  1.00e+00]
[ 0.00e+00  1.00e+00  1.00e+00]
[-1.00e+00  1.00e+00  0.00e+00]
[ 1.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  1.00e+00 -1.00e+00]
[ 0.00e+00 -1.00e+00  1.00e+00]

[ 0.00e+00]
[-3.91e+00]
[-3.91e+00]
[-6.91e+00]
[-6.93e-01]
[-6.93e-01]
[-6.93e-01]
[-6.93e-01]

[1, 2, 1, 1, 1, 1, 1]
2.8873132919750377 5.7746265726524575 11.542511122440452


In [ ]:
import copy
import numpy as np
from corsair import units
from corsair.optimization.variable import Variable
from corsair.optimization import Formulation, Constant

x   = Variable(name = 'x', guess = 1, units = '-', size = 0, description = 'The X variable')
y   = Variable(name = 'y', guess = 1, units = '-', size = 0, description = 'The Y variable')
z   = Variable(name = 'z', guess = 1, units = '-', size = 0, description = 'The Z variable')
cst = Constant(name = 'c', value = 2.0, units = '-', size = 0, description = 'A constant')

objective = x/y
constraints = [
    y <= 3 + x ,
    y >= 10
              ]

f = Formulation(objective, constraints)
from corsair.optimization.solve import solve
f.solverOptions.solveType = 'sp'
f.solverOptions.solver = 'cvxopt'
# f.solverOptions.tol = 1e-8
rs = solve(f)
rs.computeSensitivities()
print(rs.result(5))
# print(rs.__dict__.keys())
# print(len(rs.intermediateSolves))

In [7]:
elementDict= {
    # "linear"           : "unknown",
    # "quadratic"        : "unknown",
    "constant"         : {"status":"unknown", "value":None },
    "monomial"         : {"status":"unknown", "leadingConstant":None, "bases":[], "exponents":[]},
    # "posynomial"       : {"status":"unknown", "leadingCoefficients":None, "monomials":[]},
    "signomial"        : {"status":"unknown", "leadingCoefficients":None, "bases":[], "exponents":[]},
    # "convex"           : "unknown",
    # "concave"          : "unknown",
    # "logconvex"        : "unknown",
    # "logconcave"       : "unknown",
    # "globalConvex"     : "unknown",
    # "globalConcave"    : "unknown",
    # "globalLogconvex"  : "unknown",
    # "globalLogconcave" : "unknown",
}

#        'yes' : Gaurenteed
# 'attainable' : Can be manipulated to yes
#  'specified' : Possible-User specified
#   'possible' : Possible
#    'unknown' : Unknown
#         'no' : Gaurenteed Not

# Global
# On bounded interval, formulation only



# print(elementDict)